name: Echo Inputs Workflow

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Environment'
        required: true
        type: choice
        options:
          - 'DEV'
          - 'QA'
          - 'PROD'
          - 'DEMO'
      REASON:
        description: 'Reason'
        required: true
        default: 'N/A'

jobs:
  echo_inputs_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        run: |
          echo "Environment: ${{ github.event.inputs.ENVIRONMENT }}"
          echo "Reason: ${{ github.event.inputs.REASON }}"

  approval:
     runs-on: ubuntu-latest
     if: ${{ github.event.inputs.ENVIRONMENT == 'PROD' }} #Runs only environment is PROD
     environment: approval
     needs: echo_inputs_job
     steps: 
       - name: Print Approval Done
         run: |
            echo "Approval Completed"
